---
title: "MeteoFrance Heatwaves Records"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

```{r libraries}
library(tidyverse)
library(heatwaveR)
library(Utilities.Package)
```


```{r data opening}

list <- list.files("Data/MeteoFrance/85", pattern=".csv", full.names = T) %>% 
  as.data.frame() %>% 
  rename(path = ".") %>% 
  filter(!str_detect(path, "champs")) %>% 
  mutate(name = gsub(".*/","",path),
         date_start = substr(name,6,9),
         date_end = substr(name,11,14))

for(i in 1:nrow(list)){
  a <- read_delim(list$path[i], 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
  if(i == 1){
    df <- a
  }else{
    df <- rbind(df,a)
  }
  
}

saveRDS(df,"Data/MeteoFrance/Data_Weather_85.rds")
df <- readRDS("Data/MeteoFrance/Data_Weather_85.rds")
```

```{r first process}

df_date <- df  %>% 
  mutate(date = as.POSIXct(strptime(AAAAMMJJHH, format = "%Y%m%d%H"))) %>% 
  group_by(NOM_USUEL) %>% 
  reframe(min_date = min(date,na.rm = T),
          max_date = max(date,na.rm = T),
          n = n())

selected_site <- df_date %>% 
  filter(n ==max(n)) %>% 
  pull(NOM_USUEL)

df_sub <- df %>% 
  dplyr::filter(NOM_USUEL == selected_site,
                !is.na(`T`)) %>% 
  dplyr::select(NOM_USUEL, LAT,LON,,AAAAMMJJHH,`T`, TN, TX, T10, T20, T50,T100) %>% 
  mutate(date = as.POSIXct(as.character(AAAAMMJJHH), format = "%Y%m%d%H",tz = "UTC"))


ggplot(df_sub)+
  # geom_hex(aes(x = date, y = `T`), bins = 10)+
  geom_line(aes(x = date, y = `T`))+
  ylab("Temperature (°C)")+
  xlab("Date")+
  theme_Bede()+
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20))

df_heatwaveR <- df_sub %>% 
  rename(t = date,
         temp = `T`) %>% 
  dplyr::select(t,temp) %>% 
  mutate(t = as.Date(t)) %>% 
  group_by(t) %>% 
  reframe(temp = max(temp,na.rm = T)) %>% 
  dplyr::filter(t > as.Date("1948-12-31"))

  

  clim <- ts2clm(df_heatwaveR, climatologyPeriod = c("1949-01-01", "2024-06-23"))
  
  event <- detect_event(clim,categories = T,minDuration = 3)
  
  res <- detect_event(clim, minDuration = 3)
  mhw <- res$clim
  
  mhw %>% 
    filter(t> as.Date("2022-01-01")) %>% 
ggplot(aes(x = t, y = temp))+
    geom_line() +
  geom_flame(aes(y2 = thresh))
  
```

```{r frequency of heatwaves as define in Perkins and Alexander (2013)}

freq_heatwave <- event %>% 
  mutate(year = substr(as.character(date_start),1,4)) %>% 
  group_by(year) %>% 
  reframe(n = n())

intensity_heatwave <- event %>% 
  mutate(year = substr(as.character(date_start),1,4)) %>% 
  group_by(year) %>% 
  reframe(intensity = sum(intensity_cumulative))

ggplot(freq_heatwave, aes(x = as.numeric(year), y = n))+
  geom_line()+
  geom_smooth(method = "gam")

ggplot(intensity_heatwave, aes(x = as.numeric(year), y = intensity))+
  geom_line()+
  geom_smooth(method = "gam")

```


