---
title: Draft -- Effect of Atmospheric Heatwaves on Reflectance and Pigment Composition of Intertidal *Nanozostera noltei*  -- Draft
author:
  - name: Simon Oiry
    orcid: 0000-0001-7161-5246
    corresponding: true
    email: oirysimon@gmail.com
    roles:
      - Investigation
      - Writing
      - Data acquisition
    affiliations:
      - Institut des Substances et Organismes de la Mer, ISOMer, Nantes Université, UR 2160, F-44000 Nantes, France
  - name: Bede Ffinian Rowe Davies
    corresponding: false
    roles: 
      - Investigation
      - Data acquisition
      - Revision
    affiliations:
      - Institut des Substances et Organismes de la Mer, ISOMer, Nantes Université, UR 2160, F-44000 Nantes, France
  - name: Philippe Rosa
    corresponding: false
    roles: 
      - Data acquisition
      - Revision
    affiliations:
      - Institut des Substances et Organismes de la Mer, ISOMer, Nantes Université, UR 2160, F-44000 Nantes, France
  - name: Augustin Debly
    corresponding: false
    roles: 
      - Investigation
      - Data acquisition
      - Revision
    affiliations:
      - Institut des Substances et Organismes de la Mer, ISOMer, Nantes Université, UR 2160, F-44000 Nantes, France
  - name: Pierre Gernez
    corresponding: false
    roles: 
      - Investigation
      - Data acquisition
      - Revision
    affiliations:
      - Institut des Substances et Organismes de la Mer, ISOMer, Nantes Université, UR 2160, F-44000 Nantes, France
  - name: Laurent Barillé
    corresponding: false
    roles: 
      - Investigation
      - Data acquisition
      - Revision
    affiliations:
      - Institut des Substances et Organismes de la Mer, ISOMer, Nantes Université, UR 2160, F-44000 Nantes, France
keywords:
  - Remote Sensing
  - Pigment Composition
  - Seagrass
  - Coastal Ecosystems
  - Heatwaves 
abstract: |
  To be written
plain-language-summary: |
  To be written
key-points:
  - An intertidal vegetation classifier has been built to be used across different study sites without losing classification accuracy. 
  - Neural Network made to accuratly discriminates intertidal seagrasses from green algae (chlorophyceae)
date: last-modified
citation:
  container-title: Remote Sensing of Environment
number-sections: true
notebook-links: false
editor_options: 
  chunk_output_type: console
csl: RSE.csl
---

# Introduction

Intertidal seagrasses play a crucial role in the ecosystem by providing habitats and feeding grounds for various marine species, supporting rich marine biodiversity, and contributing significantly to primary production and carbon sequestration [@unsworth2022planetary ; @sousa2019blue]. These seagrasses are essential in maintaining the health of coastal ecosystems by stabilizing sediments, filtering water, and serving as indicators of environmental changes due to their sensitivity to water quality variations [@zoffoli2021decadal]. The interactions between seagrass meadows and their associated herbivores further enhance the delivery of ecosystem services, including coastal protection and fisheries support [@jankowska2019stabilizing ; @zoffoli2023remote ; @gardner2018global]. Understanding and preserving these ecosystems are vital for maintaining the biodiversity and productivity of coastal regions [@scott2018role ; @ramesh2020seagrass].

Despite their crucial role in marine ecosystems, intertidal seagrasses face numerous threats that compromise their health and functionality. Coastal development and human activities are primary threats. These activities not only reduce the available habitat for seagrasses but also increase water turbidity, which limits light penetration and hampers photosynthesis [@waycott2009accelerating]. Seagrasses are also threatened by nutrient enrichment from agricultural and urban runoff, which can lead to eutrophication. This condition promotes the overgrowth of algal blooms that compete with seagrasses for light and nutrients, further stressing these important plants [@thomsen2023meadow] (Oiry et al. 2024). Pollution from industrial and agricultural fields sources introduces harmful chemicals and heavy metals into coastal waters, posing toxic risks to seagrass health. These pollutants can affect the physiological processes of seagrasses, reducing their growth and survival rates [@sevgi2022bitkilerde] Additionally, invasive species can out compete native seagrasses for resources, altering community structure and function [@simpson2016distribution].

Heatwaves, exacerbated by climate change, pose a growing threat to seagrasses. Marine Heatwaves (MHW), defined by @hobday2016hierarchical as prolonged discrete anomalously warm water events, and Atmospheric Heatwaves (AHW), defined by @perkins2013measurement as periods of at least three consecutive days with temperatures exceeding the 90th percentile, cause severe physiological stress on seagrasses [@sawall2021chronically; @deguette2022physiological]. At the interface between the land and oceans, intertidal seagrasses are exposed to both MHW and AHW. Heatwaves have profound impacts on seagrasses, with their effects varying based on species and geographic location. For instance, the seagrass *Zostera marina* exhibits high susceptibility to elevated sea surface temperatures during winter and spring, leading to advanced flowering, high mortality rates, and reduced biomass [@sawall2021chronically]. Similarly, *Cymodocea nodosa* shows increased photosynthetic activity during heatwaves but suffers negative effects on photosynthetic performance and leaf biomass during recovery [@deguette2022physiological]. Additionally, different populations of *Zostera marina* along the European thermal gradient exhibit varied photophysiological responses during the recovery phase of heatwaves, indicating differential adaptation capabilities among populations [@winters2011effects]. These events intensify other stressors, such as overgrazing and seed burial, compromising sexual recruitment [@guerrero2020heat].

Bleaching and browning events of seagrass beds have been observed following episodes of intense heat along the Brittany coast of France (Pers. obs.) then affecting leaf color, which are expected to alter leaf reflectance. Remote sensing is increasingly being utilized to monitor marine ecosystems, including seagrass meadows. By using spectral indices, such as the Normalized Difference Vegetation Index (NDVI) and the Soil-Adjusted Vegetation Index (SAVI), or by analyzing specific spectral patterns, remote sensing can effectively quantify vegetation health over time [@huete2012vegetation ; @kloos2021agricultural ; @carlan2020identifying ; @akbar2020mangrove]. Through the Water Framework Directive and the Marine Strategy Framework Directive, Europe is promoting remote sensing techniques for habitat mapping, as these methods enable the monitoring of extensive areas over time [@papathanasopoulou2019satellite]. This study will experimentally test the hypothesis that warm events modify the pigment composition and reflectance of seagrass, linking these changes with satellite remote sensing.

# Material & Methods

## Heatwaves detection and characterisation

### Air temperature

Since January 1, 2024, Meteo France weather data has been freely and openly accessible. Hourly weather data for the French coast of the Atlantic and the Channel has been downloaded using a [custom script](https://github.com/SigOiry/HeatWave_Seagrasses/blob/main/MeteoFrance_Extraction.qmd), as no API has been developed for downloading this data at the date of this study. Weather stations located within 10 kilometers of the coastline were considered, but only those with a minimum of 30 years of data were included to ensure accurate climatology reconstruction. Among the 156 weather station that are within the 10km threshold of coastline, 36 had enough data to reconstruct the climatology. Hourly data has been aggregated to daily mean temperatures.

### Water temperature

not done yet !

## Experiment

### Sampling and Acclimation of seagrasses

Seagrass was sampled from a *Nanozostera noltei* (dwarf eelgrass, syn. Zostera noltei) meadow on Noirmoutier Island, France (46°57'32.0"N 2°10'37.0"W) at low tide in June 2024. A shovel was used to sample seagrass from an area of 30 cm by 15 cm and 10 cm deep, maintaining the sediment structure and avoiding damage to the rhizomes and the leafs of the seagrass. The seagrass, along with sediment, meiofauna, and macrofauna, was placed in plastic trays. To avoid hydric stress during transportation, seawater was added to each tray. Simultaneously, seawater was sampled from a nearby site and transported to the lab, where it was filtered using a 0.22 µm nitrocellulose filter to remove all suspended particulate matter. This water was used in the acclimation tank and the intertidal chambers. The seagrasses were acclimated for two weeks with a water temperature of 17°C, matching the temperature at the time of sampling, and with light of 150 µmol.s-1.m-2 of PAR photons [@akbar2020mangrove]. A wave generator was used in the tank to circulate and reoxygenate the water.

### Experimental design

Two intertidal chambers from [ElectricBlue](https://electricblue.eu/intertidal-chamber) were used to simulate tidal cycles and control water temperature during high tide and air temperature during low tide. One chamber served as the control, while the other was used for the experimental treatment. The control chamber was maintained at temperatures representative of the typical seasonal conditions: water temperatures between 18°C and 19°C and air temperatures between 18°C and 23°C. For the experimental treatment, the air temperature was set to mimic an atmospheric heatwave that occurred over the seagrass meadow of Porh Saint-Guénël, Plouharnel, France (47°35'40.0"N, 3°07'30.0"W) from August 26, 2021, to September 6, 2021. On the first day of the experiment, air temperatures in the experimental chamber were set to range from 23°C at night to 35°C during the day, with a daily increase of 1°C. The water temperature in the experimental chamber was similarly adjusted to reflect the heatwave conditions, starting from the normal seasonal range (18°C) and gradually increasing to simulate the rising temperatures experienced during the heatwave (+0.5°C daily). This setup aimed to replicate the thermal stress experienced by the seagrass meadow during the actual heatwave event.

```{r chamber profiles}
#| cache: true
#| echo: false
#| eval: false
#| warning: false

library(MapRs)
library(tidyverse)
library(Utilities.Package)

experimental_design <- Make_Chamber_Profile(min_Air_Temp_control = 19,
                                            max_Air_Temp_control = 23,
                                            min_Air_Temp_test = 23,
                                            max_Air_Temp_test = 35,
                                            min_Water_Temp_control= 18, 
                                            max_Water_Temp_control = 18,
                                            min_Water_Temp_test = 18,
                                            max_Water_Temp_test = 18,
                                            date_start = "2024-07-22 21:00:00",
                                            date_end = "2024-07-26 23:00:00",
                                            low_tide_time = "2024-07-23 12:00:00",
                                            High_Tide_Until = "2024-07-24 09:00:00",
                                            daily_increase_Air_Test = 1,
                                            daily_increase_Water_Test = 0.5,
                                            daily_increase_Air_Control = 0,
                                            daily_increase_Water_Control = 0,
                                            sunrise = 6.25,
                                            sunset = 22,
                                            max_light_intensity = 120,
                                            export_profile = F,
                                            Tide = "both",
                                            night_tide = T,
                                            time_step = 60, 
                                            Save_Experiment = F, 
                                            Experiment_Name = "HW5_24072024_to_26072024")

df_control <- experimental_design$Control_df %>% 
  dplyr::filter(Time > as.POSIXct("2024-07-24 00:00:00", format = "%Y-%m-%d %H:%M", tz = "UTC")) %>% 
  dplyr::mutate(scenario = "Control")
df_test <- experimental_design$Test_df %>% 
  dplyr::filter(Time > as.POSIXct("2024-07-24 00:00:00", format = "%Y-%m-%d %H:%M", tz = "UTC")) %>% 
  dplyr::mutate(scenario = "Test")

df <- df_control %>% 
  bind_rows(df_test)

polygon_table <-   df %>% 
  group_by(tide_ID) %>% 
  reframe(Tide_Status = unique(Tide_Status), 
          xmin = min(Time),
          xmax = max(Time),
          T_min = min(Temp_Air,Temp_Water),
          T_max = max(Temp_Air,Temp_Water)) %>% 
  ungroup() %>% 
  mutate( ymin = min(T_min),
          ymax = max(T_max)) %>% 
  rename(Tide = Tide_Status) %>% 
  mutate(Tide = case_when(Tide == "High_Tide" ~ "High",
                          TRUE ~ "Low"))

water_polyline <- df %>% 
  dplyr::filter(scenario == "Test") %>% 
  dplyr::filter(Tide_Status == "High_Tide") 

air_polylines <- df %>% 
  dplyr::filter(scenario == "Test") %>% 
  dplyr::filter(Tide_Status == "Low_Tide")

max_air_temp <- df %>% 
  dplyr::filter(scenario == "Test") %>% 
  dplyr::filter(Tide_Status == "Low_Tide") %>% 
  group_by(tide_ID) %>% 
  dplyr::filter(Temp == max(Temp)) %>% 
  dplyr::filter(Temp >=35)

  

df %>% 
  dplyr::filter(scenario == "Test") %>% 
ggplot()+
  geom_line(aes(x = Time, y = Temp))+
  geom_rect(data = polygon_table , aes(ymin = ymin, ymax = ymax, xmin = xmin, xmax =xmax, fill = Tide, group = tide_ID),alpha = 0.1) +
  geom_line(data = water_polyline, aes(x = Time, y = Temp, group = tide_ID), color = "blue3", linewidth = 1)+
  scale_x_datetime(date_breaks = "12 hour", date_labels = "%H:%M") +

  geom_line(data = air_polylines, aes(x = Time, y = Temp, group = tide_ID), color = "red4", linewidth = 1)+
   ggforce::geom_mark_ellipse(data=max_air_temp,
                 aes(x=Time,
                     y=Temp,
                     label = paste0(Temp, " °C"),
                     group = tide_ID),
                     # description=Description),
                 size=0.3,
                 fill = "goldenrod",
                 con.colour = "goldenrod4",
                 show.legend=F,
                 label.fontsize = 25,
                 label.hjust = 0.5,
                 con.size = 2,
                 alpha=0.8,
  expand = unit(2, "mm") , 
  radius = unit(2, "mm") ,
  label.fill = "grey90",
  label.buffer = unit(5, "mm"))+
  ylim(c(17,39))+

  theme_Bede()

```



# Bibliography
